packages:
  - "apps/**"
  - "packages/**"
  - "services/**"

allowBuilds:
  bcrypt: true
  esbuild: true
  unrs-resolver: true

catalog:
  "react": 19.2.0
  "react-dom": 19.2.0

  "next": 16.2.4
  "next-themes": 0.4.6

  "astro": 6.4.2
  "@astrojs/react": 5.0.6

  "framer-motion": 12.38.0
  "gsap": 3.15.0
  "lenis": 1.3.23

  "tailwindcss": 4.2.4
  "@tailwindcss/postcss": 4.2.4
  "@tailwindcss/vite": 4.3.0

  "class-variance-authority": 0.7.1
  "clsx": 2.1.1
  "tailwind-merge": 3.5.0
  "tw-animate-css": 1.4.0

  "@radix-ui/react-slot": 1.2.3
  "@radix-ui/react-dialog": 1.1.15
  "radix-ui": 1.4.3

  "@tanstack/react-query": 5.100.14
  "date-fns": 4.1.0
  "lucide-react": 1.14.0
  "react-hook-form": 7.54.2
  "react-hot-toast": 2.6.0
  "react-router-dom": 7.15.1
  "recharts": 2.15.4
  "zustand": 5.0.13

  "typescript": 5.9.2
  "typescript-eslint": 8.59.2

  "eslint": 9.39.1
  "@eslint/js": 9.39.1
  "eslint-config-next": 16.2.4
  "eslint-plugin-react-hooks": 7.1.1
  "eslint-plugin-react-refresh": 0.5.2

  "globals": 17.6.0

  "prettier": 3.8.3
  "turbo": 2.9.8
  "tsx": 4.21.0

  "vite": 7.1.5
  "@vitejs/plugin-react": 5.1.0

  "@types/node": 22.15.3
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2

  "dotenv": 17.4.2
  "express": 5.2.1
  "socket.io": 4.8.3
  "mongoose": 9.6.0
  "ioredis": 5.10.1
  "zod": 4.3.6

  "cors": 2.8.6
  "helmet": 8.1.0
  "compression": 1.8.1
  "cookie-parser": 1.4.7
  "morgan": 1.10.1
  "express-rate-limit": 8.4.1

  "bcrypt": 6.0.0
  "jsonwebtoken": 9.0.3

  "multer": 2.1.1
  "cloudinary": 2.10.0

  "axios": 1.15.2

  "@supabase/supabase-js": 2.105.1

  "@types/bcrypt": 6.0.0
  "@types/cookie-parser": 1.4.10
  "@types/cors": 2.8.19
  "@types/express": 5.0.6
  "@types/jsonwebtoken": 9.0.10
  "@types/multer": 2.1.0

onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - sharp
  - unrs-resolver
  - msw